name = "Healpix"
uuid = "9f4e344d-96bc-545a-84a3-ae6b9e1b672b"
authors = ["Maurizio Tomasi <maurizio.tomasi@unimi.it>"]
version = "4.0.1"

[deps]
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Libsharp = "ac8d63fe-4615-43ae-9860-9cd4a3820532"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CFITSIO = "1"
Libsharp = "0.2"
RecipesBase = "1"
julia = "1.3"
StaticArrays = "1"
