name = "Healpix"
uuid = "0fe3d3e8-c00f-11e8-2353-b5858a79f927"
authors = ["Maurizio Tomasi <maurizio.tomasi@unimi.it>"]
version = "2.0.0"

[deps]
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
